name: Website Monitor


on:
schedule:
- cron: '*/5 * * * *' # every hour at minute 0
workflow_dispatch: # manual trigger


jobs:
check:
runs-on: ubuntu-latest


steps:
- uses: actions/checkout@v3


- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.11'


- name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install -r requirements.txt


- name: Run website check
env:
WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
PHONE_NUMBER_ID: ${{ secrets.PHONE_NUMBER_ID }}
WHATSAPP_ACCESS_TOKEN: ${{ secrets.WHATSAPP_ACCESS_TOKEN }}
TO_WHATSAPP: ${{ secrets.TO_WHATSAPP }}
REQUEST_TIMEOUT: '10'
run: |
python check_site.py
